export default {
  FETCH_POSTS: 'FETCH_POSTS',
  POST_MESSAGE: 'POST_MESSAGE',
  DELETE_POST: 'DELETE_POST',
  CLEAN_POSTS: 'CLEAN_POSTS',
  AUTH: 'AUTH',
  AUTH_CLEAR: 'AUTH_CLEAR',
  AUTH_CLEAR_ERROR: 'AUTH_CLEAR_ERROR',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  EDIT_ACCOUNT: 'EDIT_ACCOUNT',
};
