export default {
  FCHAT_MESSAGES_LOADING: 'FCHAT_MESSAGES_LOADING',
  FCHAT_MESSAGES_SUCCESS: 'FCHAT_MESSAGES_SUCCESS',
  FCHAT_MESSAGES_ERROR: 'FCHAT_MESSAGES_ERROR',
  ADD_MESSAGE: 'ADD_MESSAGE',
};
