export default {
  FCHAT_MESSAGES_LOADING: 'FCHAT_MESSAGES_LOADING',
  FCHAT_MESSAGES_SUCCESS: 'FCHAT_MESSAGES_SUCCESS',
  FCHAT_MESSAGES_ERROR: 'FCHAT_MESSAGES_ERROR',
  POST_CHAT_MESSAGE_SUCCESS: 'POST_CHAT_MESSAGE_SUCCESS',
  DELETE_CHAT_MESSAGE_SUCCESS: 'DELETE_CHAT_MESSAGE_SUCCESS',
};
