export default {
  FETCH_CHAT_MESSAGES: 'FETCH_CHAT_MESSAGES',
  POST_CHAT_MESSAGE: 'POST_CHAT_MESSAGE',
  //POST_CHAT_MESSAGE_SUCCESS: 'POST_CHAT_MESSAGE_SUCCESS',
  DELETE_CHAT_MESSAGE: 'DELETE_CHAT_MESSAGE',
  //DELETE_CHAT_MESSAGE_SUCCESS: 'DELETE_CHAT_MESSAGE_SUCCESS',
  CLEAN_CHAT: 'CLEAN_CHAT',
  AUTH: 'AUTH',
  LOGOUT: 'LOGOUT',
};
