export default {
  FETCH_CHAT_MESSAGES: 'FETCH_CHAT_MESSAGES',
  POST_CHAT_MESSAGE: 'POST_CHAT_MESSAGE',
  DELETE_CHAT_MESSAGE: 'DELETE_CHAT_MESSAGE',
  CLEAN_CHAT: 'CLEAN_CHAT',
  AUTH: 'AUTH',
  AUTH_CLEAR: 'AUTH_CLEAR',
};
